#!/bin/bash

# Verifica se o arquivo Cousine.zip existe na pasta Downloads
if [[ ! -f ~/Downloads/Cousine.zip ]]; then
    echo "Erro: O arquivo Cousine.zip não foi encontrado em ~/Downloads."
    echo "Por favor, baixe o arquivo Cousine.zip na pasta Downloads e tente novamente."
    exit 1
fi

# Verifica se o nala está instalado
if command -v nala >/dev/null 2>&1; then
    echo "Nala já está instalado."
else
    echo "Nala não está instalado. Instalando agora..."
    # Atualiza a lista de pacotes e instala o nala
    sudo apt update && sudo apt install -y nala
    if [ $? -eq 0 ]; then
        echo "Nala foi instalado com sucesso."
    else
        echo "Falha ao instalar o nala. Verifique sua conexão ou permissões."
        exit 1
    fi
fi

mkdir -p ~/.fonts
unzip ~/Downloads/Cousine.zip -d ~/.fonts
fc-cache -vf
gsettings set org.gnome.desktop.interface monospace-font-name 'Cousine Nerd Font Mono 12'
echo -e "Nerd Fonts: \ue0b0 \ue0a0"

#Neovim
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
#curl -LO https://github.com/neovim/neovim/releases/download/v0.11.2/nvim-linux-x86_64.appimage
chmod u+x nvim-linux-x86_64.appimage
sudo mkdir -p /opt/nvim
sudo mv nvim-linux-x86_64.appimage /opt/nvim/nvim
echo 'export PATH="$PATH:/opt/nvim/"' >> ~/.bashrc

sudo apt install python3 python3-pip python3-venv xclip python3-pynvim luarocks ripgrep fd-find npm nodejs tree-sitter-cli build-essential lua5.1 -y
git clone https://github.com/amonetlol/nvim_gruvbox.git  ~/.config/nvim
rm -rf ~/.config/nvim/.git
rm -rf ~/.config/nvim/.gitignore

# fastfetch
curl -LO https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-amd64.deb
sudo apt install ./fastfetch-linux-amd64.deb
mkdir -p "${HOME}/.config/fastfetch/"
curl -sSLo "${HOME}/.config/fastfetch/config.jsonc" https://raw.githubusercontent.com/ChrisTitusTech/mybash/main/config.jsonc

# starship
curl -sS https://starship.rs/install.sh | sh
echo 'eval "$(starship init bash)"' >> ~/.bashrc
# setup 1
# wget -O ~/.config/starship.toml https://raw.githubusercontent.com/amonetlol/terminal-bash/refs/heads/main/starship.toml
# setup 2
wget -O ~/.config/starship.toml https://raw.githubusercontent.com/amonetlol/terminal-bash/refs/heads/main/starship-titus.toml

# Bibata cursor
sudo apt install bibata-cursor-theme -y
gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'

#### Temas e Icones ####
# https://github.com/yeyushengfan258/Reversal-gtk-theme
# https://github.com/yeyushengfan258/McMuse-icon-theme
# sudo apt install gnome-themes-extra gtk2-engines-murrine

# configurando alias
echo "alias up2='sudo nala update && sudo nala upgrade -y'" >> ~/.bashrc
echo "alias .r='source ~/.bashrc'" >> ~/.bashrc
echo "alias al='nvim ~/.bashrc'" >> ~/.bashrc
echo "alias ft='fastfetch --logo small'" >> ~/.bashrc
echo "alias nv='nvim'" >> ~/.bashrc
echo "alias nup='nvim --headless -c \"Lazy update\" -c \"qa\"'" >> ~/.bashrc
echo "alias fup='flatpak update -y'" >> ~/.bashrc
source ~/.bashrc
