#!/bin/bash

mkdir -p ~/.fonts
unzip ~/Downloads/Cousine.zip -d ~/.fonts
fc-cache -vf

#Neovim
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
chmod u+x nvim-linux-x86_64.appimage
sudo mkdir -p /opt/nvim
sudo mv nvim-linux-x86_64.appimage /opt/nvim/nvim
echo 'export PATH="$PATH:/opt/nvim/"' >> ~/.bashrc

sudo apt install python3 python3-pip python3-venv yt-dlp xclip python3-pynvim luarocks ripgrep fd-find npm nodejs tree-sitter-cli build-essential -y
git clone https://github.com/amonetlol/neovim-kickstart-config.git ~/.config/nvim
rm -rf ~/.config/nvim/.git
rm -rf ~/.config/nvim/.gitignore

# fastfetch
curl -LO https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-amd64.deb
sudo apt install ./fastfetch-linux-amd64.deb
mkdir -p "${HOME}/.config/fastfetch/"
curl -sSLo "${HOME}/.config/fastfetch/config.jsonc" https://raw.githubusercontent.com/ChrisTitusTech/mybash/main/config.jsonc

# starship
curl -sS https://starship.rs/install.sh | sh
echo 'eval "$(starship init bash)"' >> ~/.bashrc
# setup 1
# wget -O ~/.config/starship.toml https://raw.githubusercontent.com/amonetlol/terminal-bash/refs/heads/main/starship.toml
# setup 2
wget -O ~/.config/starship.toml https://raw.githubusercontent.com/amonetlol/terminal-bash/refs/heads/main/starship-titus.toml

# Bibata cursor
sudo apt install bibata-cursor-theme -y
gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'

# configurando alias
echo "alias up2='sudo apt update && sudo apt upgrade -y'" >> ~/.bashrc
echo "alias .r='source ~/.bashrc'" >> ~/.bashrc
echo "alias al='nvim ~/.bashrc'" >> ~/.bashrc
echo "alias ft='fastfetch --logo small'" >> ~/.bashrc
echo "alias nv='nvim'" >> ~/.bashrc
echo "alias nup='nvim --headless -c \"Lazy update\" -c \"qa\"'" >> ~/.bashrc
echo "alias fup='flatpak update -y'" >> ~/.bashrc
source ~/.bashrc
